export const VehicleRentCategoryType = {
   CAR: 'CAR',
   MOTORCYCLE: 'MOTORCYCLE',
   THREE_WHILEERS_OR_QUADS: 'THREE_WHILEERS_OR_QUADS',
   TRUCKS: 'TRUCKS',
   PASSENGER_TRANSPORT_VEHICLES: 'PASSENGER_TRANSPORT_VEHICLES',
   AGRICULTURAL_MACHINERY: 'AGRICULTURAL_MACHINERY',
   ENGINS: 'ENGINS',
   MARINE_AIR_VEHICLES: 'MARINE_AIR_VEHICLES',
}

export type VehicleRentCategoryType = keyof typeof VehicleRentCategoryType
