export const VehicleRentType = {
   // CAR
   CAR_SEDAN: 'CAR_SEDAN',
   CAR_HATCHBACK: 'CAR_HATCHBACK',
   CAR_SUV: 'CAR_SUV',
   CAR_CROSSOVER: 'CAR_CROSSOVER',
   CAR_COUPE: 'CAR_COUPE',
   CAR_CABRIOLET: 'CAR_CABRIOLET',
   CAR_STATION_WAGON: 'CAR_STATION_WAGON',
   CAR_MINIVAN: 'CAR_MINIVAN',
   CAR_SPORTS_CAR: 'CAR_SPORTS_CAR',
   CAR_SUPERCAR: 'CAR_SUPERCAR',
   CAR_OFF_ROAD_SUV: 'CAR_OFF_ROAD_SUV',

   // MOTORCYCLE
   MOTORCYCLE_SCOOTER: 'MOTORCYCLE_SCOOTER',
   MOTORCYCLE_MOPED: 'MOTORCYCLE_MOPED',
   MOTORCYCLE_STANDARD: 'MOTORCYCLE_STANDARD',
   MOTORCYCLE_CRUISER: 'MOTORCYCLE_CRUISER',
   MOTORCYCLE_SPORT_BIKE: 'MOTORCYCLE_SPORT_BIKE',
   MOTORCYCLE_TOURING_BIKE: 'MOTORCYCLE_TOURING_BIKE',
   MOTORCYCLE_ADVENTURE: 'MOTORCYCLE_ADVENTURE',
   MOTORCYCLE_MOTOCROSS: 'MOTORCYCLE_MOTOCROSS',
   MOTORCYCLE_ELECTRIC_MOTORCYCLE: 'MOTORCYCLE_ELECTRIC_MOTORCYCLE',

   // THREE_WHILEERS_OR_QUADS
   THREE_WHILEERS_OR_QUADS_QUAD: 'THREE_WHILEERS_OR_QUADS_QUAD',
   THREE_WHILEERS_OR_QUADS_UTV: 'THREE_WHILEERS_OR_QUADS_UTV',
   THREE_WHILEERS_OR_QUADS_TRIKE: 'THREE_WHILEERS_OR_QUADS_TRIKE',
   THREE_WHILEERS_OR_QUADS_TUK_TUK: 'THREE_WHILEERS_OR_QUADS_TUK_TUK',

   // TRUCKS
   TRUCKS_PICKUP_TRUCK: 'TRUCKS_PICKUP_TRUCK',
   TRUCKS_LIGHT_TRUCK: 'TRUCKS_LIGHT_TRUCK',
   TRUCKS_FLATBED_TRUCK: 'TRUCKS_FLATBED_TRUCK',
   TRUCKS_CARGO_TRUCK: 'TRUCKS_CARGO_TRUCK',
   TRUCKS_REFRIGERATED_TRUCK: 'TRUCKS_REFRIGERATED_TRUCK',
   TRUCKS_DUMP_TRUCK: 'TRUCKS_DUMP_TRUCK',
   TRUCKS_TANKER_TRUCK: 'TRUCKS_TANKER_TRUCK',
   TRUCKS_SEMI_TRAILER_TRUCK: 'TRUCKS_SEMI_TRAILER_TRUCK',
   TRUCKS_CAR_CARRIER_TRUCK: 'TRUCKS_CAR_CARRIER_TRUCK',
   TRUCKS_LOGGING_TRUCK: 'TRUCKS_LOGGING_TRUCK',
   TRUCKS_GARBAGE_TRUCK: 'TRUCKS_GARBAGE_TRUCK',
   TRUCKS_TOW_TRUCK: 'TRUCKS_TOW_TRUCK',

   // PASSENGER_TRANSPORT_VEHICLES
   PASSENGER_TRANSPORT_VEHICLES_MINIBUS: 'PASSENGER_TRANSPORT_VEHICLES_MINIBUS',
   PASSENGER_TRANSPORT_VEHICLES_CITY_BUS:
      'PASSENGER_TRANSPORT_VEHICLES_CITY_BUS',
   PASSENGER_TRANSPORT_VEHICLES_INTERCITY_BUS:
      'PASSENGER_TRANSPORT_VEHICLES_INTERCITY_BUS',
   PASSENGER_TRANSPORT_VEHICLES_SHUTTLE_VAN:
      'PASSENGER_TRANSPORT_VEHICLES_SHUTTLE_VAN',

   // AGRICULTURAL_MACHINERY
   AGRICULTURAL_MACHINERY_TRACTOR: 'AGRICULTURAL_MACHINERY_TRACTOR',
   AGRICULTURAL_MACHINERY_COMBINE_HARVESTER:
      'AGRICULTURAL_MACHINERY_COMBINE_HARVESTER',
   AGRICULTURAL_MACHINERY_SEEDER: 'AGRICULTURAL_MACHINERY_SEEDER',
   AGRICULTURAL_MACHINERY_UTILITY_FARM_VEHICLE:
      'AGRICULTURAL_MACHINERY_UTILITY_FARM_VEHICLE',

   // ENGINS
   ENGINS_BULLDOZER: 'ENGINS_BULLDOZER',
   ENGINS_EXCAVATOR: 'ENGINS_EXCAVATOR',
   ENGINS_BACKHOE_LOADER: 'ENGINS_BACKHOE_LOADER',
   ENGINS_FORKLIFT: 'ENGINS_FORKLIFT',
   ENGINS_SKID_STEER_LOADER: 'ENGINS_SKID_STEER_LOADER',
   ENGINS_ROAD_ROLLER: 'ENGINS_ROAD_ROLLER',
   ENGINS_CRANE: 'ENGINS_CRANE',

   // MARINE_AIR_VEHICLES
   MARINE_AIR_VEHICLES_BOAT: 'MARINE_AIR_VEHICLES_BOAT',
   MARINE_AIR_VEHICLES_SHIP: 'MARINE_AIR_VEHICLES_SHIP',
   MARINE_AIR_VEHICLES_JET_SKI: 'MARINE_AIR_VEHICLES_JET_SKI',
   MARINE_AIR_VEHICLES_DRONE: 'MARINE_AIR_VEHICLES_DRONE',
   MARINE_AIR_VEHICLES_HELICOPTER: 'MARINE_AIR_VEHICLES_HELICOPTER',
   MARINE_AIR_VEHICLES_AIRPLANE: 'MARINE_AIR_VEHICLES_AIRPLANE',
}

export type VehicleRentType = keyof typeof VehicleRentType
