export const TransactionFlowType = {
   COMPANY_TO_COMPANY: 'COMPANY_TO_COMPANY',
   COMPANY_TO_CLIENT: 'COMPANY_TO_CLIENT',
   COMPANY_TO_DRIVER: 'COMPANY_TO_DRIVER',
   COMPANY_TO_SITE: 'COMPANY_TO_SITE',
   COMPANY_TO_ADMIN: 'COMPANY_TO_ADMIN',

   CLIENT_TO_COMPANY: 'CLIENT_TO_COMPANY',
   CLIENT_TO_CLIENT: 'CLIENT_TO_CLIENT',
   CLIENT_TO_DRIVER: 'CLIENT_TO_DRIVER',
   CLIENT_TO_SITE: 'CLIENT_TO_SITE',
   CLIENT_TO_ADMIN: 'CLIENT_TO_ADMIN',

   DRIVER_TO_COMPANY: 'DRIVER_TO_COMPANY',
   DRIVER_TO_CLIENT: 'DRIVER_TO_CLIENT',
   DRIVER_TO_DRIVER: 'DRIVER_TO_DRIVER',
   DRIVER_TO_SITE: 'DRIVER_TO_SITE',
   DRIVER_TO_ADMIN: 'DRIVER_TO_ADMIN',

   SITE_TO_COMPANY: 'SITE_TO_COMPANY',
   SITE_TO_CLIENT: 'SITE_TO_CLIENT',
   SITE_TO_DRIVER: 'SITE_TO_DRIVER',
   SITE_TO_SITE: 'SITE_TO_SITE',
   SITE_TO_ADMIN: 'SITE_TO_ADMIN',

   ADMIN_TO_COMPANY: 'ADMIN_TO_COMPANY',
   ADMIN_TO_CLIENT: 'ADMIN_TO_CLIENT',
   ADMIN_TO_DRIVER: 'ADMIN_TO_DRIVER',
   ADMIN_TO_SITE: 'ADMIN_TO_SITE',
   ADMIN_TO_ADMIN: 'ADMIN_TO_ADMIN',
} as const

export type TransactionFlowType = keyof typeof TransactionFlowType
