export const TransactionMethodType = {
   CASH_TO_CASH: 'CASH_TO_CASH',
   CASH_TO_RAPIDE_WALLET: 'CASH_TO_RAPIDE_WALLET',
   CASH_TO_ORANGE_MONEY: 'CASH_TO_ORANGE_MONEY',
   CASH_TO_MVOLA: 'CASH_TO_MVOLA',
   CASH_TO_CARD: 'CASH_TO_CARD',

   RAPIDE_WALLET_TO_CASH: 'RAPIDE_WALLET_TO_CASH',
   RAPIDE_WALLET_TO_RAPIDE_WALLET: 'RAPIDE_WALLET_TO_RAPIDE_WALLET',
   RAPIDE_WALLET_TO_ORANGE_MONEY: 'RAPIDE_WALLET_TO_ORANGE_MONEY',
   RAPIDE_WALLET_TO_MVOLA: 'RAPIDE_WALLET_TO_MVOLA',
   RAPIDE_WALLET_TO_CARD: 'RAPIDE_WALLET_TO_CARD',

   ORANGE_MONEY_TO_CASH: 'ORANGE_MONEY_TO_CASH',
   ORANGE_MONEY_TO_RAPIDE_WALLET: 'ORANGE_MONEY_TO_RAPIDE_WALLET',
   ORANGE_MONEY_TO_ORANGE_MONEY: 'ORANGE_MONEY_TO_ORANGE_MONEY',
   ORANGE_MONEY_TO_MVOLA: 'ORANGE_MONEY_TO_MVOLA',
   ORANGE_MONEY_TO_CARD: 'ORANGE_MONEY_TO_CARD',

   MVOLA_TO_CASH: 'MVOLA_TO_CASH',
   MVOLA_TO_RAPIDE_WALLET: 'MVOLA_TO_RAPIDE_WALLET',
   MVOLA_TO_ORANGE_MONEY: 'MVOLA_TO_ORANGE_MONEY',
   MVOLA_TO_MVOLA: 'MVOLA_TO_MVOLA',
   MVOLA_TO_CARD: 'MVOLA_TO_CARD',

   CARD_TO_CASH: 'CARD_TO_CASH',
   CARD_TO_RAPIDE_WALLET: 'CARD_TO_RAPIDE_WALLET',
   CARD_TO_ORANGE_MONEY: 'CARD_TO_ORANGE_MONEY',
   CARD_TO_MVOLA: 'CARD_TO_MVOLA',
   CARD_TO_CARD: 'CARD_TO_CARD',
} as const

export type TransactionMethodType = keyof typeof TransactionMethodType
