export const ExpressStatusType = {
   PENDING: 'PENDING',
   CANCELLED: 'CANCELLED',
   ADMIN_CANCELLED: 'ADMIN_CANCELLED',
   REJECTED: 'REJECTED',
   CHECKED: 'CHECKED',
   READY_FOR_PICK_UP: 'READY_FOR_PICK_UP',
   SENDER_NOT_FOUND: 'SENDER_NOT_FOUND',
   PICKED: 'PICKED',
   ARRIVED_IN_WAREHOUSE: 'ARRIVED_IN_WAREHOUSE',
   READY_FOR_DELIVERY: 'READY_FOR_DELIVERY',
   ON_DELIVERY: 'ON_DELIVERY',
   DELIVERED: 'DELIVERED',
   RECEIVER_NOT_FOUND: 'RECEIVER_NOT_FOUND',
   PAY: 'PAY',
   CLIENT_DID_NOT_PAY: 'CLIENT_DID_NOT_PAY',
   LOST_ON_PICKED: 'LOST_ON_PICKED',
   LOST_IN_WAREHOUSE: 'LOST_IN_WAREHOUSE',
   LOST_ON_DELIVERY: 'LOST_ON_DELIVERY',
   BROKEN_ON_PICKED: 'BROKEN_ON_PICKED',
   BROKEN_IN_WAREHOUSE: 'BROKEN_IN_WAREHOUSE',
   BROKEN_ON_DELIVERY: 'BROKEN_ON_DELIVERY',
} as const

export type ExpressStatusType = keyof typeof ExpressStatusType

export const ExpressStatusColor = {
   [ExpressStatusType.PENDING]: 'yellow',
   [ExpressStatusType.CANCELLED]: 'red',
   [ExpressStatusType.ADMIN_CANCELLED]: 'red',
   [ExpressStatusType.REJECTED]: 'red',
   [ExpressStatusType.CHECKED]: 'green',
   [ExpressStatusType.READY_FOR_PICK_UP]: 'green',
   [ExpressStatusType.SENDER_NOT_FOUND]: 'orange',
   [ExpressStatusType.PICKED]: 'sky-blue',
   [ExpressStatusType.ARRIVED_IN_WAREHOUSE]: 'purple',
   [ExpressStatusType.READY_FOR_DELIVERY]: 'blue',
   [ExpressStatusType.ON_DELIVERY]: 'sky-blue',
   [ExpressStatusType.DELIVERED]: 'blue',
   [ExpressStatusType.RECEIVER_NOT_FOUND]: 'orange',
   [ExpressStatusType.PAY]: 'brown',
   [ExpressStatusType.CLIENT_DID_NOT_PAY]: 'rose',
   [ExpressStatusType.LOST_ON_PICKED]: 'gray',
   [ExpressStatusType.LOST_IN_WAREHOUSE]: 'gray',
   [ExpressStatusType.LOST_ON_DELIVERY]: 'gray',
   [ExpressStatusType.BROKEN_ON_PICKED]: 'red',
   [ExpressStatusType.BROKEN_IN_WAREHOUSE]: 'red',
   [ExpressStatusType.BROKEN_ON_DELIVERY]: 'red',
}
