/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnauthorizedRouteImport } from './routes/unauthorized'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppTransactionsIndexRouteImport } from './routes/app/transactions/index'
import { Route as AppMartIndexRouteImport } from './routes/app/mart/index'
import { Route as AppMartOrdersRouteImport } from './routes/app/mart/orders'
import { Route as AppMartAllProductsRouteImport } from './routes/app/mart/all-products'
import { Route as AppMartAddProductRouteImport } from './routes/app/mart/add-product'
import { Route as AppMartAddManyProductsRouteImport } from './routes/app/mart/add-many-products'
import { Route as AppMartMartIdRouteImport } from './routes/app/mart/$martId'
import { Route as AppMartEditMartIdRouteImport } from './routes/app/mart/edit/$martId'

const UnauthorizedRoute = UnauthorizedRouteImport.update({
  id: '/unauthorized',
  path: '/unauthorized',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppTransactionsIndexRoute = AppTransactionsIndexRouteImport.update({
  id: '/transactions/',
  path: '/transactions/',
  getParentRoute: () => AppRoute,
} as any)
const AppMartIndexRoute = AppMartIndexRouteImport.update({
  id: '/mart/',
  path: '/mart/',
  getParentRoute: () => AppRoute,
} as any)
const AppMartOrdersRoute = AppMartOrdersRouteImport.update({
  id: '/mart/orders',
  path: '/mart/orders',
  getParentRoute: () => AppRoute,
} as any)
const AppMartAllProductsRoute = AppMartAllProductsRouteImport.update({
  id: '/mart/all-products',
  path: '/mart/all-products',
  getParentRoute: () => AppRoute,
} as any)
const AppMartAddProductRoute = AppMartAddProductRouteImport.update({
  id: '/mart/add-product',
  path: '/mart/add-product',
  getParentRoute: () => AppRoute,
} as any)
const AppMartAddManyProductsRoute = AppMartAddManyProductsRouteImport.update({
  id: '/mart/add-many-products',
  path: '/mart/add-many-products',
  getParentRoute: () => AppRoute,
} as any)
const AppMartMartIdRoute = AppMartMartIdRouteImport.update({
  id: '/mart/$martId',
  path: '/mart/$martId',
  getParentRoute: () => AppRoute,
} as any)
const AppMartEditMartIdRoute = AppMartEditMartIdRouteImport.update({
  id: '/mart/edit/$martId',
  path: '/mart/edit/$martId',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/app/': typeof AppIndexRoute
  '/app/mart/$martId': typeof AppMartMartIdRoute
  '/app/mart/add-many-products': typeof AppMartAddManyProductsRoute
  '/app/mart/add-product': typeof AppMartAddProductRoute
  '/app/mart/all-products': typeof AppMartAllProductsRoute
  '/app/mart/orders': typeof AppMartOrdersRoute
  '/app/mart': typeof AppMartIndexRoute
  '/app/transactions': typeof AppTransactionsIndexRoute
  '/app/mart/edit/$martId': typeof AppMartEditMartIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sign-in': typeof SignInRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/app': typeof AppIndexRoute
  '/app/mart/$martId': typeof AppMartMartIdRoute
  '/app/mart/add-many-products': typeof AppMartAddManyProductsRoute
  '/app/mart/add-product': typeof AppMartAddProductRoute
  '/app/mart/all-products': typeof AppMartAllProductsRoute
  '/app/mart/orders': typeof AppMartOrdersRoute
  '/app/mart': typeof AppMartIndexRoute
  '/app/transactions': typeof AppTransactionsIndexRoute
  '/app/mart/edit/$martId': typeof AppMartEditMartIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/app/': typeof AppIndexRoute
  '/app/mart/$martId': typeof AppMartMartIdRoute
  '/app/mart/add-many-products': typeof AppMartAddManyProductsRoute
  '/app/mart/add-product': typeof AppMartAddProductRoute
  '/app/mart/all-products': typeof AppMartAllProductsRoute
  '/app/mart/orders': typeof AppMartOrdersRoute
  '/app/mart/': typeof AppMartIndexRoute
  '/app/transactions/': typeof AppTransactionsIndexRoute
  '/app/mart/edit/$martId': typeof AppMartEditMartIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/sign-in'
    | '/unauthorized'
    | '/app/'
    | '/app/mart/$martId'
    | '/app/mart/add-many-products'
    | '/app/mart/add-product'
    | '/app/mart/all-products'
    | '/app/mart/orders'
    | '/app/mart'
    | '/app/transactions'
    | '/app/mart/edit/$martId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sign-in'
    | '/unauthorized'
    | '/app'
    | '/app/mart/$martId'
    | '/app/mart/add-many-products'
    | '/app/mart/add-product'
    | '/app/mart/all-products'
    | '/app/mart/orders'
    | '/app/mart'
    | '/app/transactions'
    | '/app/mart/edit/$martId'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/sign-in'
    | '/unauthorized'
    | '/app/'
    | '/app/mart/$martId'
    | '/app/mart/add-many-products'
    | '/app/mart/add-product'
    | '/app/mart/all-products'
    | '/app/mart/orders'
    | '/app/mart/'
    | '/app/transactions/'
    | '/app/mart/edit/$martId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  SignInRoute: typeof SignInRoute
  UnauthorizedRoute: typeof UnauthorizedRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unauthorized': {
      id: '/unauthorized'
      path: '/unauthorized'
      fullPath: '/unauthorized'
      preLoaderRoute: typeof UnauthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/transactions/': {
      id: '/app/transactions/'
      path: '/transactions'
      fullPath: '/app/transactions'
      preLoaderRoute: typeof AppTransactionsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/mart/': {
      id: '/app/mart/'
      path: '/mart'
      fullPath: '/app/mart'
      preLoaderRoute: typeof AppMartIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/mart/orders': {
      id: '/app/mart/orders'
      path: '/mart/orders'
      fullPath: '/app/mart/orders'
      preLoaderRoute: typeof AppMartOrdersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/mart/all-products': {
      id: '/app/mart/all-products'
      path: '/mart/all-products'
      fullPath: '/app/mart/all-products'
      preLoaderRoute: typeof AppMartAllProductsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/mart/add-product': {
      id: '/app/mart/add-product'
      path: '/mart/add-product'
      fullPath: '/app/mart/add-product'
      preLoaderRoute: typeof AppMartAddProductRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/mart/add-many-products': {
      id: '/app/mart/add-many-products'
      path: '/mart/add-many-products'
      fullPath: '/app/mart/add-many-products'
      preLoaderRoute: typeof AppMartAddManyProductsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/mart/$martId': {
      id: '/app/mart/$martId'
      path: '/mart/$martId'
      fullPath: '/app/mart/$martId'
      preLoaderRoute: typeof AppMartMartIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/mart/edit/$martId': {
      id: '/app/mart/edit/$martId'
      path: '/mart/edit/$martId'
      fullPath: '/app/mart/edit/$martId'
      preLoaderRoute: typeof AppMartEditMartIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
  AppMartMartIdRoute: typeof AppMartMartIdRoute
  AppMartAddManyProductsRoute: typeof AppMartAddManyProductsRoute
  AppMartAddProductRoute: typeof AppMartAddProductRoute
  AppMartAllProductsRoute: typeof AppMartAllProductsRoute
  AppMartOrdersRoute: typeof AppMartOrdersRoute
  AppMartIndexRoute: typeof AppMartIndexRoute
  AppTransactionsIndexRoute: typeof AppTransactionsIndexRoute
  AppMartEditMartIdRoute: typeof AppMartEditMartIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppIndexRoute: AppIndexRoute,
  AppMartMartIdRoute: AppMartMartIdRoute,
  AppMartAddManyProductsRoute: AppMartAddManyProductsRoute,
  AppMartAddProductRoute: AppMartAddProductRoute,
  AppMartAllProductsRoute: AppMartAllProductsRoute,
  AppMartOrdersRoute: AppMartOrdersRoute,
  AppMartIndexRoute: AppMartIndexRoute,
  AppTransactionsIndexRoute: AppTransactionsIndexRoute,
  AppMartEditMartIdRoute: AppMartEditMartIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  SignInRoute: SignInRoute,
  UnauthorizedRoute: UnauthorizedRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
